Integrate cargo fmt into pipeline. Don't update rustup in case it is already installed to prevent reinstall.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -38,8 +38,6 @@ jobs:
       run: |
         if [ -d "$HOME/.cargo/" ] && [ -d "$HOME/.rustup/" ]; then
             echo "Rust is already installed. Skipping installation."
-            rustup update
-            rustup override set nightly
             rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy
         else
             echo "Rust is not installed. Installing via rustup..."
@@ -48,6 +46,13 @@ jobs:
 
     - name: Show rust version
       run: rustc --version
+
+    - name: Check formatting
+      run: |
+        cargo +nightly fmt --all --check || {
+          echo "Formatting failed — please run 'cargo +nightly fmt --all' locally before pushing.";
+          exit 1;
+        }
 
     - name: Build
       run: cargo build --all-targets --all-features
