Add labels through github cli.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -75,66 +75,66 @@ jobs:
             cargo install cargo-edit
         fi
 
-    # - name: Show rust version
-    #   run: rustc --version
+    - name: Show rust version
+      run: rustc --version
 
-    # - name: Format code
-    #   if: env.AUTO_FORMAT == 'true'
-    #   run: cargo +nightly fmt --all
+    - name: Format code
+      if: env.AUTO_FORMAT == 'true'
+      run: cargo +nightly fmt --all
 
-    # - name: Check formatting
-    #   if: env.AUTO_FORMAT != 'true'
-    #   run: |
-    #     cargo +nightly fmt --all --check || {
-    #       echo "Formatting failed — please run 'cargo +nightly fmt --all' locally before pushing.";
-    #       exit 1;
-    #     }
+    - name: Check formatting
+      if: env.AUTO_FORMAT != 'true'
+      run: |
+        cargo +nightly fmt --all --check || {
+          echo "Formatting failed — please run 'cargo +nightly fmt --all' locally before pushing.";
+          exit 1;
+        }
     
-    # # Allow dirty flag added for convinience. Be careful when auto-formatting is enabled.
-    # - name: Clippy apply suggestions
-    #   if: env.AUTO_FORMAT == 'true'
-    #   run: RUSTFLAGS="-Dclippy::all" cargo +nightly clippy --all-targets --all-features --fix --allow-dirty
+    # Allow dirty flag added for convinience. Be careful when auto-formatting is enabled.
+    - name: Clippy apply suggestions
+      if: env.AUTO_FORMAT == 'true'
+      run: RUSTFLAGS="-Dclippy::all" cargo +nightly clippy --all-targets --all-features --fix --allow-dirty
 
-    # # Still need to run clippy as well, because cargo clippy fix makes errors into warnings. See: https://github.com/rust-lang/rust-clippy/discussions/9979
-    # - name: Clippy
-    #   run: RUSTFLAGS="-Dclippy::all" cargo +nightly clippy --all-targets --all-features
+    # Still need to run clippy as well, because cargo clippy fix makes errors into warnings. See: https://github.com/rust-lang/rust-clippy/discussions/9979
+    - name: Clippy
+      run: RUSTFLAGS="-Dclippy::all" cargo +nightly clippy --all-targets --all-features
 
-    # # Replaces cargo test and checks test coverage.
-    # - name: Test coverage
-    #   run: |
-    #     cargo +nightly llvm-cov clean --workspace;
-    #     cargo +nightly llvm-cov --no-report --workspace --all-features --all-targets;
-    #     cargo +nightly llvm-cov --no-report --workspace --all-features --doctests;
-    #     cargo +nightly llvm-cov report --fail-under-regions 40;
+    # Replaces cargo test and checks test coverage.
+    - name: Test coverage
+      run: |
+        cargo +nightly llvm-cov clean --workspace;
+        cargo +nightly llvm-cov --no-report --workspace --all-features --all-targets;
+        cargo +nightly llvm-cov --no-report --workspace --all-features --doctests;
+        cargo +nightly llvm-cov report --fail-under-regions 40;
         
-    # # Needed to catch dangling references in documentation.
-    # - name: Build documentation
-    #   run: cargo +nightly doc --no-deps;
+    # Needed to catch dangling references in documentation.
+    - name: Build documentation
+      run: cargo +nightly doc --no-deps;
 
-    # - name: Show API diff
-    #   run: |
-    #     cargo test public_api::tests::print_changes -- --nocapture --ignored
+    - name: Show API diff
+      run: |
+        cargo test public_api::tests::print_changes -- --nocapture --ignored
 
-    # - name: Check SemVer
-    #   if: env.VERSION_BUMP != 'None'
-    #   run: |
-    #     case ${VERSION_BUMP,,} in
-    #       patch)
-    #         cargo set-version --bump patch
-    #         ;;
-    #       minor)
-    #         cargo set-version --bump minor
-    #         ;;
-    #       major)
-    #         cargo set-version --bump major
-    #         ;;
-    #       *)
-    #         if cargo test public_api::tests::is_patch -- --ignored; then
-    #             cargo set-version --bump patch
-    #         elif cargo test public_api::tests::is_minor -- --ignored; then
-    #             echo "Consider bumping minor version."
-    #         else
-    #             echo "Consider bumping major version."
-    #         fi
-    #         ;;
-    #     esac
+    - name: Check SemVer
+      if: env.VERSION_BUMP != 'None'
+      run: |
+        case ${VERSION_BUMP,,} in
+          patch)
+            gh pr edit "$PR_NUMBER" --add-label "patch"
+            ;;
+          minor)
+            gh pr edit "$PR_NUMBER" --add-label "minor"
+            ;;
+          major)
+            gh pr edit "$PR_NUMBER" --add-label "major"
+            ;;
+          *)
+            if cargo test public_api::tests::is_patch -- --ignored; then
+                gh pr edit "$PR_NUMBER" --add-label "patch"
+            elif cargo test public_api::tests::is_minor -- --ignored; then
+                gh pr edit "$PR_NUMBER" --add-label "minor"
+            else
+                gh pr edit "$PR_NUMBER" --add-label "major"
+            fi
+            ;;
+        esac
